[package]
name = "rexkv"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lz4_flex = "0.11"
napi = { version = "3", default-features = false, features = ["napi4", "async"] }
napi-derive = "3"
redb = "2"
tokio = { version = "1", features = ["sync"] }

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = true
opt-level = 3
panic = "abort"
